googleplaystore/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

main/urls.py
from django.conf.urls import url
from . import views
app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/', views.search, name="search"),
    url(r'^details/(?P<result_id>[0-9]+)', views.details, name="details")
]

main/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models

class SearchString(models.Model):
	searchstring = models.CharField(max_length=250)
	searched_time = models.DateTimeField(default=datetime.now())
	amount_of_time_searched = models.IntegerField(default='0')

	def __str__(self):
		return "%s - %s" % (self.searchstring, self.amount_of_time_searched)

class Result(models.Model):
	app_id = models.CharField(max_length=250)
	app_name = models.CharField(max_length=250)
	dev_name = models.CharField(max_length=250)
	app_icon = models.CharField(max_length=250)
	searched_by = models.ForeignKey(SearchString)

	def __str__(self):
		return "%s - %s" % (self.app_name, self.app_id)

main/views.py
from __future__ import unicode_literals
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from bs4 import BeautifulSoup
import requests
from .models import Result, SearchString
import sys

def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render({}, request))

def search(request):
	if request.method == 'POST':
		if SearchString.objects.filter(searchstring = request.POST.get('qry')).exists():

			searchstr = SearchString.objects.filter(searchstring = request.POST.get('qry')).get()
			searchstr.amount_of_time_searched += 1
			searchstr.save()
			result_list = Result.objects.filter(searched_by__searchstring__exact = request.POST.get('qry'))

			return render(request, 'result_list.html', {
				'result_list': result_list
			})

		else:
			url  = 'https://play.google.com/store/search?q='+request.POST.get('qry')+'&c=apps'

			try:
				raw  = requests.get(url)
				soup = BeautifulSoup(raw.text, 'html.parser')
				apps = soup.find_all(class_="card-content")
				searchstr = SearchString(searchstring=request.POST.get('qry').lower(), amount_of_time_searched=1)
				searchstr.save()
			except requests.exceptions.RequestException as e:
				print(e)
				sys.exit(1)

			ids = []
			for app in apps[:10]:
				app_id = app.find("span", {"class": "preview-overlay-container"})['data-docid']
				app_name = app.find("img", {"class": "cover-image"})['alt']
				cover_image = app.find("img", {"class": "cover-image"})['src']
				dev_name = app.find(class_="subtitle").get_text()

				if Result.objects.filter(app_id = app_id).exists():
					toAppend = Result.objects.filter(app_id = app_id).get()
					ids.append(toAppend.id)
				else:
					res = Result(searched_by=searchstr, app_id=app_id, app_name=app_name, dev_name=dev_name, app_icon=cover_image)
					res.save()
					ids.append(res.id)

			result_list = Result.objects.filter(pk__in=ids)
			return render(request, 'result_list.html', {
				'result_list': result_list
			})

	
	return HttpResponseRedirect("/")

def details(request, result_id):
	if Result.objects.filter(pk = result_id).exists():

		result_list = Result.objects.filter(pk = result_id).get()
		return render(request, 'details.html', {
			'result_list': result_list
		})

	else:
		return render(request, 'details.html', {'error_message': 'Nothing Found!'})

main/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title> Django Google Play Search </title>
	{% load staticfiles %}
	<link rel="icon" href="{% static 'images/fav.ico' %}" type="image/gif" sizes="16x16">
	<meta name="description" content="">
    <meta name="keywords" content="">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <style type="text/css">
    	.container{
			text-align: center;
			margin: 0 auto;
			width: 500px;
			/*padding-top: 20%;*/
		}
		input, input[placeholder]{
		    text-align:center;
		}
    </style>
</head>
<body>
	{% block body %}
	{% endblock %}
	<p style="margin-left: 42%;padding-top: 35%">Made with <span style="color: #e74c3c">&hearts;</span> by Subham Bhattacharjee</a></p>
</body>
</html>

main/templates/details.html
{% extends 'base.html' %}
{% block body %}
<style type="text/css">
	html {
	    font-family: Lato, 'Helvetica Neue', Arial, Helvetica, sans-serif;
	    font-size: 14px;
	}

	h5 {
	    font-size: 1.28571429em;
	    font-weight: 700;
	    line-height: 1.2857em;
	    margin: 0;
	}

	.card {
	    font-size: 1em;
	    overflow: hidden;
	    padding: 0;
	    border: none;
	    border-radius: .28571429rem;
	    box-shadow: 0 1px 3px 0 #d4d4d5, 0 0 0 1px #d4d4d5;
	}

	.card-block {
	    font-size: 1em;
	    position: relative;
	    margin: 0;
	    padding: 1em;
	    border: none;
	    border-top: 1px solid rgba(34, 36, 38, .1);
	    box-shadow: none;
	}

	.card-img-top {
	    display: block;
	    width: 100%;
	    height: auto;
	}

	.card-title {
	    font-size: 1.28571429em;
	    font-weight: 700;
	    line-height: 1.2857em;
	}

	.card-text {
	    clear: both;
	    margin-top: .5em;
	    color: rgba(0, 0, 0, .68);
	}

	.card-inverse .btn {
	    border: 1px solid rgba(0, 0, 0, .05);
	}

	.profile {
	    position: absolute;
	    top: -12px;
	    display: inline-block;
	    overflow: hidden;
	    box-sizing: border-box;
	    width: 25px;
	    height: 25px;
	    margin: 0;
	    border: 1px solid #fff;
	    border-radius: 50%;
	}

	.profile-avatar {
	    display: block;
	    width: 100%;
	    height: auto;
	    border-radius: 50%;
	}

	.profile-inline {
	    position: relative;
	    top: 0;
	    display: inline-block;
	}

	.profile-inline ~ .card-title {
	    display: inline-block;
	    margin-left: 4px;
	    vertical-align: top;
	}
</style>
<div class="container">
	{% if error_message %}
		<p><strong> {{ error_message }} </strong></p>
		<a href="{% url 'main:index' %}">Go Back</a>
	{% else %}
        <div class="card card-inverse card-info">
        	<p><b> {{ result_list.app_name }} </b></p>
            <img class="card-img-top" src="{{ result_list.app_icon }}">
            <div class="card-block">
                <figure class="profile profile-inline">
                    <img src="{{ result_list.app_icon }}" class="profile-avatar" alt="">
                </figure>
                <h4 class="card-title">{{ result_list.app_name }}</h4>
                <div class="card-text">
                    {{ result_list.dev_name }}
                    {{ result_list.app_id }}
                </div>
            </div>
        </div>
        <a onclick="window.history.back()"><button class="btn btn-primary btn-block">Go Back</button></a>
	{% endif %}
</div>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
	<p><b>Search Google Play Store </b></p>
	<form action="{% url 'main:search' %}" method="POST" class="form-horizontal">
	{% csrf_token %}
		<div class="form-group">
		    <input type="text" id="input" class="form-control" name="qry" placeholder="Enter Your Query" autocomplete="off" pattern="^[0-9a-zA-Z]+$" required><br>
			<input type="submit" value="SUBMIT" class="btn btn-primary btn-lg">
	    </div>
	</form>
</div>
{% endblock %}

main/templates/result_list.html
{% extends 'base.html' %}
{% block body %}
{% if result_list %}
<h3>Here goes all the results:</h3><a style="float: right;" href="{% url 'main:index' %}"><button class="btn btn-primary">Go Back</button></a>
<table class="table table-striped">
    <thead>
      <tr>
      	<th>Icon</th>
        <th>App ID</th>
        <th>App Name</th>
        <th>Dev Name</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>
    {% for list in result_list %}
      <tr>
        <td><img src="{{ list.app_icon }}"></td>
        <td>{{ list.app_id }}</td>
        <td>{{ list.app_name }}</td>
        <td>{{ list.dev_name }}</td>
        <td><a href="{% url 'main:details' list.id %}">More Details</a></td>
      </tr>
    {% endfor %}
    </tbody>
</table>
<a style="float: right;" href="{% url 'main:index' %}"><button class="btn btn-primary">Go Back</button></a>
{% else %}
	<h2>Nope! nothing found!</h2>
	<a onclick="window.history.back()"><button class="btn btn-primary btn-block">Go Back</button></a>
{% endif %}
{% endblock %}